[[section-system-scope-and-context]]

== Kontextabgrenzung


[role="arc42help"]
****
.Inhalt
Die Kontextsicht grenzt das System, für das Sie die Architektur entwickeln, von allen Nachbarsystemen ab. Sie legt damit die wesentlichen externen Schnittstellen fest.
Stellen Sie sicher, dass die Schnittstellen mit allen relevanten Aspekten (was wird übertragen, in welchem Format wird übertragen, welches Medium wird verwendet, ...) spezifiziert wird, auch wenn einige populäre Diagramme (wie z.B. das UML Use-Case Diagramm) nur ausgewählte Aspekte der Schnittstelle darstellen.

.Motivation
Die Schnittstellen zu Nachbarsystemen gehören zu den kritischsten Aspekten eines Projektes. Stellen Sie rechtzeitig sicher, dass Sie diese komplett verstanden haben.

.Form
*  Diverse Kontextdiagramme (siehe folgende Abschnitte)
*  Listen von Nachbarsystemen mit deren Schnittstellen.
****

Die folgenden Unterkapitel zeigen die Einbettung unseres Systems in seine Umgebung.

=== Fachlicher Kontext

[role="arc42help"]
****
.Inhalt
Festlegung aller footnote:[alle,Zwar sind wir an vielen Stellen zu Pragmatismus bereit – hier
jedoch bestehen wir auf der vollständigen Auflistung aller *(a-l-l-e-r)* Nachbarsysteme.
Zu viele Projekte sind daran gescheitert, dass sie ihre Nachbarn nicht kannten :-(]
Nachbarsysteme des betrachteten Systems mit Spezifikation aller
fachlichen Daten, die mit diesen ausgetauscht werden. Zusätzlich evtl. Datenformate
und Protokolle der Kommunikation mit Nachbarsystemen und der Umwelt
(falls diese nicht erst bei den spezifischen Bausteinen präzisiert wird.

.Motivation
Verstehen, welche (logischen) Informationen mit Nachbarsystemen (in welcher Form)
ausgetauscht werden.

.Form
Logisches Kontextdiagramm, in der UML z.B. simuliert durch Klassendiagramme, Use Case Diagramme,
Kommunikationsdiagramme - kurz durch alle Diagramme, die das System als Black Box
darstellen und die Schnittstellen zu den Nachbarsystemen (mehr oder weniger ausführlich)
beschreiben.

Alternativ oder ergänzend können Sie einfach eine Tabelle verwenden. Der Titel gibt den Namen Ihres Systems wieder; die drei Spalten sind: Nachbarsystem, Input, Output. Auch so kommen Sie zu einer kompletten Schnittstellenbeschreibung.
****


=== Technischer- oder Verteilungskontext

[role="arc42help"]
****
.Inhalt
Festlegung der Kanäle zwischen Ihrem System, den Nachbarsystemen und der Umwelt;
Zusätzlich eine Mapping-Tabelle, welcher logische Input (aus 3.1) über welchen Kanal ein- oder ausgegeben wird.

.Motivation
Verstehen, über welche Medien Informationen mit Nachbarsystemen bzw. der Umwelt ausgetauscht werden.

.Form
z.B.: UML Deployment-Diagramm mit den Kanälen zu Nachbarsystemen, begleitet von einer Mapping-Tabelle Kanal x Input/Output.
****

=== Externe Schnittstellen

==== Payment-Schnittstelle

[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle
|Payment-Schnittstelle
|Beschreibung|
Schnittstelle zum Zahlungsanbieter
|Version
| Wird durch Zahlungsanbieter definiert

|Änderungen gegenüber Vorversion
| Keine

|Wer hat geändert und warum?
| -

|Verantwortlicher Ansprechpartner / Rolle
| Zahlungsdienstleister
|===

Da der Zahlunsanbieter noch nicht definiert ist, können bezüglich des Protokolles
oft nur Annahmen getroffen werden.

===== Fachliche Abläufe
* Kreditkartendaten müssen sicher (verschlüsselt) übermittelt werden
* Zahlungsdienstleister bestätitg Zahlung oder generiert Fehler
* Fehlerbehandlung auf seite OTS

===== Mengengerüste
* Annahme Normal-Auslastung: 30000 Transaktionen pro Tag (Annahme 2 Performances pro Tag)
* Annahme Peak-Szenario: 15000 Transaktionen in 10min müssen bewältigt werden können
* Zeit für eine Transaktion darf maximal 10 Sekunden in Anspruch nehmen
(Vergleiche auch "Qualitätsziele" Kapitel 1.2)

===== Syntax: Daten und Formate
Wird durch den Zahlungsanbieter defniert (TBD)

===== Syntax: Ablauf der Schnittstelle
Wird durch den Zahlungsanbieter defniert (TBD)

===== Technische Infrastruktur
* HTTP / REST (Webservice)

===== Fehler und Ausnahmebehandlung
* Validierungs-Fehler (Validierung wird durch Zahlungsdienstleister durchgeführt)
** Karte ungültig
** Kredit-Limite erreicht
* Timeout
* Protokoll-Fehler

===== Einschränkungen und Voraussetzungen
* Voraussetzung: OTS muss beim Zahlungsanbieter registirert sein
* Auf der Schnittstelle müssen Transaktionen parallel ausgeführt werden können
* Schnittstelle muss 7x24 verfügbar sein (SLA noch offen)

===== Metainformation der Schnittstelle
noch nicht verfübar (TBD)

===== Beispiele für Nutzung und Daten
noch nicht verfügbar (TBD)


==== E-Mail-Schnittstelle

[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle
| E-Mail-Schnittstelle
|Beschreibung
| Schnittstelle zum verdenden der Bestellungsbestätigung und Tickets
|Version
| 1.0
|Änderungen gegenüber Vorversion
| Keine
|Wer hat geändert und warum?
| -

|Verantwortlicher Ansprechpartner / Rolle
| Entwicklungsteam
|===

===== Fachliche Abläufe
* für jede erfolgreiche Buchung wird ein Buchungsbestätigungs E-Mail versandt

===== Mengengerüste
* Das System muss 30000 E-Mails pro Tag verarbeiten und versenden können.
* Unter Hochlast muss das System muss bis zu 15000 Mails innerhalb von 10min entgegennehmen können,
die Mails müssen jedoch nicht in diesem Zeitraum versandt werden

===== Syntax: Daten und Formate
* Standard SMTP
* Message Enthält:
** Buchungsnummer
** Ticket
** Begleittext

===== Syntax: Ablauf der Schnittstelle
* Standard SMTP

===== Technische Infrastruktur
* Mail-System des X-Centers

===== Fehler und Ausnahmebehandlung
* Mail System ist nicht erreichbar / Timeout
* Mail konnte vom Mail-System nicht entgegen genommen werden

===== Einschränkungen und Voraussetzungen
(siehe Mengengerüste)

===== Metainformation der Schnittstelle
noch nicht vorhanden (TBD)

===== Beispiele für Nutzung und Daten
(siehe Syntax: Daten und Formate)


==== User-Schnittstelle

[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle
| User-Schnittstelle
|Beschreibung
| Web Applikation über welche Online-User sowie Box-Office-User zugreiffen
|Version
| 1.0
|Änderungen gegenüber Vorversion
| Keine
|Wer hat geändert und warum?
| -
|Verantwortlicher Ansprechpartner / Rolle
| Architektur-Team
|===

Diese Schnittstelle ist zentraler Bestandteil der gesammt-Archtektur, weswegen
an dieser Stelle nicht explizit auf Punkte eingegangen wird, welche anderenorts
beschrieben wurden.

===== Fachliche Abläufe
===== Mengengerüste
(Siehe "Qualitätsziele" Kapitel 1.2)

===== Syntax: Daten und Formate
* HTTP

===== Syntax: Ablauf der Schnittstelle
===== Technische Infrastruktur
===== Fehler und Ausnahmebehandlung
===== Einschränkungen und Voraussetzungen
===== Metainformation der Schnittstelle
===== Beispiele für Nutzung und Daten



[role="arc42help"]
****
.Inhalt
Spezifikation der Kommunikationskanäle, die ihr System mit den Nachbar-Systemen und der Umwelt verbinden.


._Externe Schnittstelle 1_

.Identifikation der Schnittstelle
[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle
|_<Name der Schnittstelle>_

|Version
|

|Änderungen gegenüber Vorversion
|

|Wer hat geändert und warum?
|

|Verantwortlicher Ansprechpartner / Rolle
|
|===

.Fachlicher Kontext der Schnittstelle

.Fachliche Abläufe
_<Diagramm oder Beschreibung der fachlichen Abläufe>_

.Fachliche Bedeutung der Daten
* _<Beschreibung der fachlichen Bedeutung>_
* Technischer Kontext
* Form der Interaktion

.Anforderungen an die Schnittstelle

.Sicherheitsanforderungen

.Mengengerüste
* Laufzeit
* Durchsatz / Datenvolumen
* Verfügbarkeit
* Protokollierung
* Archivierung

.Beteiligte Resourcen

.Syntax: Daten und Formate
*   Datenformate
*   Gültigkeits- und Plausibilitätsregeln
*   Codierung, Zeichensätze
*   Konfigurationsdaten

.Syntax: Methoden/Funktionen
* Prüfdaten

.Ablauf der Schnittstelle
* fachliche oder technischer Ablauf

.Semantik
* Nebenwirkungen, Konsequenzen

.Technische Infrastruktur
* Technische Protokolle

.Fehler- und Ausnahmebehandlung
* Welche Fehler werden erkannt?
* Wie werden sie intern behandelt?
* Welche Fehler werden nach aussen gegeben?

.Einschränkungen und Voraussetzungen
* Berechtigungen
* Zeitliche Einschränkungen
* Parallele Benutzung
* Voraussetzungen zur Nutzung

.Betrieb der Schnittstelle

.Metainformationen der Schnittstelle
* Verantwortliche
* Kosten der Nutzung
* Organisatorisches
* Versionierung

.Beispiele für Nutzung und Daten
* Beispieldaten
* Beispielabläufe / -interaktionen
* Programmierbeispiele

****
