[[section-system-scope-and-context]]

== Kontextabgrenzung

Die folgenden Unterkapitel zeigen die Einbettung unseres Systems in seine Umgebung.

=== Fachlicher Kontext
Siehe Kapitel <<section-building-block-view,5.1>>

=== Technischer- oder Verteilungskontext
Siehe Kapitel <<section-deployment-view,7.1>>

=== Externe Schnittstellen

==== Payment-Schnittstelle

[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle | Payment-Schnittstelle Datatrans LightboxMode
|Beschreibung| Einbindung der Zahlungsschnittstelle mittels JavaScript
|Version | 1.0.2
|Änderungen gegenüber Vorversion | nicht relevant, da Neuimplementierung
|Wer hat geändert und warum? | -
|Verantwortlicher Ansprechpartner / Rolle | Datatrans-Support
|===

Für die Abwicklung der Zahlungen wird die Payment-Schnittstelle von Datatrans verwendet.
Datatrans stellt verschiedene Varianten zur Verfügung,
die auf der Webseite
footnote:[https://www.datatrans.ch/de/angebot/zahlungsloesungen/webshop]
erläutert werden.
Die Variante "Lightbox Mode" hat folgende Vorteile:

* einfache Integration,
* der komplette Zahlungsablauf läuft extern ab
* daher kann ein vereinfachtes Zertifizierungsverfahren verwendet werden

Die Variante "Hidden/Ajax Mode" ermöglichst es zwar,
die Zahlungsmaske direkt ins OTS zu integrieren,
stellt aber erhöhte Anforderungen für die Zertifizierung.
footnote:[https://www.datatrans.ch/de/e-payment/pcidss/pci-dss-3-ausgangslage]
Daher wird auf die Variante "Hidden/Ajax Mode" verzichtet.

Eine detaillierte Beschreibung der Variante findet sich hier.
footnote:[https://pilot.datatrans.biz/showcase/doc/Technical_Implementation_Guide.pdf]


===== Fachliche Abläufe
* Der Benutzer klickt auf Bezahlen
* mittels JavaScript wird das von Datatrans zur Verfügung gestellte Popover geöffnet
* der Benutzer wählt die gewünschte Zahlungsart aus
* Der Benutzer gibt die Kreditkartendaten ein und klickt auf Bezahlen
* je nach Status sendet Datatrans mittels POST-Parametern die Zahlungsdaten an die successUrl, die errorURL oder die cancelURL


===== Mengengerüste
* Annahme Normal-Auslastung: 10000 Transaktionen pro Tag (Annahme 2 Performances pro Tag mit 15000 Plätzen und durchschnittlich 3 Karten pro Bestellung)
* Annahme Peak-Szenario: 10000 Transaktionen in 10min müssen bewältigt werden können
* Zeit für eine Transaktion darf maximal 10 Sekunden in Anspruch nehmen
(Vergleiche auch "Qualitätsziele" Kapitel 1.2)

===== Syntax: Daten und Formate
Kann mittels JavaScript in die Seite eingebunden werden und als Funktion aufgerufen werden.
[source, JavaScript]
----
<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="https://pilot.datatrans.biz/upp/payment/js/datatrans-1.0.2.js"></script>
<form id="paymentForm" data-merchant-id="1100004624" data-amount="1000"
data-currency="CHF" data-refno="123456789" data-sign="30916165706580013">
<button id="paymentButton">Pay</button></form>
<script type="text/javascript">$("#paymentButton").click(function(){Datatrans.startPayment({'form':'#paymentForm'});});</script>
----
Übergabeparameter:
|===
| Name | Pflicht | Datentyp | Bemerkung
| merchantId  | X | N10  | die Händler-ID wird von Datatrans vergeben
| amount | X | int | Betrag in Rappen bzw. Cent
| currency | X | A3 | ISO-Code der Währung (CHF, USD, EUR usw.)
| refno | X | AN18 | Referenznummer
| sign | X | |  Hash-Wertes des Requestes ( siehe Kapitel 6.2.3 der Datatrans-Doc)
|successUrl | | | URL die noch einer erfolgreichen Zahlung aufgerufen wird
|errorUrl | | |
|cancelUrl | | |
|===

Zusätzliche Parameter sind möglich. Details siehe Datatrans-Doc.
footnote:[https://pilot.datatrans.biz/showcase/doc/Technical_Implementation_Guide.pdf]


Rückgabewerte

Je nach Status wird eine separate Seite aufgerufen.
Mittels POST-Parametern werden die Informationen zurückgeliefert.
|===
| Name | Datentyp | Bedeutung
| uppTransactionId| N18 | Transaktionsnummer
| refNo | AN18 | ID, die beim Request angegeben wurde
| responseCode | N4 |
|===

Details siehe Datatrans-Doc.


===== Syntax: Ablauf der Schnittstelle
Wird durch den Zahlungsanbieter definiert (TBD)

===== Technische Infrastruktur
* Serverseitig keine speziellen Voraussetzungen notwendig (wird als Scriptcode in die Webseite eingebunden)
* Clientseitig muss der Browser JavaScript aktiviert haben


===== Fehler und Ausnahmebehandlung
* Timeout (Datatrans-Seite ist nicht erreichbar)
* Datatrans liefert eine Fehlercode (siehe Kapitel 8 Datatrans-doc)


===== Voraussetzungen
* OTS muss beim Zahlungsanbieter registriert sein (gültige merchantId notwendig)
* Auf der Schnittstelle müssen Transaktionen parallel ausgeführt werden können (ist gewährleistet)
* Schnittstelle muss 7x24 verfügbar sein (genaues SLA noch offen)

===== Einschränkungen
* Datatrans unterstützt folgende Browserversionen: Chrome 28, Firefox 31, IE9, Safari 6, Opera 24

Hinweis: Als Randbedingung sollen alle Firefox-Versionen seit 2012 unterstützt werden.
Firefox 31 ist allerdings im Juli 2014 veröffentlicht worden.
Unserer Meinung nach sollte eine Anpassung der Randbindung aber möglich sein, damit die Schnittstelle trotzdem verwendet werden kann.

===== Metainformation der Schnittstelle
noch nicht verfügbar (TBD)

===== Beispiele für Nutzung und Daten
siehe https://www.datatrans.ch/showcase/authorisation/lightbox-mode


==== E-Mail-Schnittstelle

[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle
| E-Mail-Schnittstelle
|Beschreibung
| Schnittstelle zum Versenden der Bestellbestätigung und Tickets
|Version
| 1.0
|Änderungen gegenüber Vorversion
| Keine
|Wer hat geändert und warum?
| -

|Verantwortlicher Ansprechpartner / Rolle
| Entwicklungsteam
|===

===== Fachliche Abläufe
* für jede erfolgreiche Buchung wird ein Buchungsbestätigung-E-Mail versandt

===== Mengengerüste
* Das System muss 10000 E-Mails pro Tag verarbeiten und versenden können.
(Annahme 2 Performances pro Tag mit 15000 Plätzen und durchschnittlich 3 Karten pro Bestellung)
* Unter Hochlast muss das System muss bis zu 10000 Mails innerhalb von 10min entgegennehmen können,
die Mails müssen jedoch nicht in diesem Zeitraum versandt werden

===== Syntax: Daten und Formate
* Standard SMTP
* Message Enthält:
** Buchungsnummer
** Ticket
** Begleittext

===== Syntax: Ablauf der Schnittstelle
* Standard SMTP

===== Technische Infrastruktur
* Mail-System des X-Centers

===== Fehler und Ausnahmebehandlung
* Mail System ist nicht erreichbar / Timeout
* Mail konnte vom Mail-System nicht entgegen genommen werden

===== Einschränkungen und Voraussetzungen
(siehe Mengengerüste)

===== Metainformation der Schnittstelle
noch nicht vorhanden (TBD)

===== Beispiele für Nutzung und Daten
(siehe Syntax: Daten und Formate)


////

Anmerkung FMO: Das GUI ist meiner Meinung nach keine Schnittstelle, sondern
(wie unten auch erwähnt) ein zentraler Bestandteil

==== User-Schnittstelle

[cols="1,1", options="header"]
|===
|Name / Bezeichnung der Schnittstelle
| User-Schnittstelle
|Beschreibung
| Web Applikation über welche Online-User sowie Box-Office-User zugreifen
|Version
| 1.0
|Änderungen gegenüber Vorversion
| Keine
|Wer hat geändert und warum?
| -
|Verantwortlicher Ansprechpartner / Rolle
| Architektur-Team
|===

Diese Schnittstelle ist zentraler Bestandteil der Gesamt-Archtektur, weswegen
an dieser Stelle nicht explizit auf Punkte eingegangen wird, welche anderenorts
beschrieben wurden.

===== Fachliche Abläufe
(Siehe Use-Cases Kapitel 1)

===== Mengengerüste
(Siehe "Qualitätsziele" Kapitel 1.2)

===== Syntax: Daten und Formate
* HTTP

////
