[[section-design-decisions]]

== Entwurfsentscheidungen

=== Datenhaltung

==== Fragestellung
Wo sollen die Daten gespeichert werden?

==== Rahmenbedingungen

Oracle 12c wird bereits verwendet.

==== Annahmen

Andere (kommerzielle) Datenbank-Managementsysteme sind nicht zulässig.

==== Entscheidungskriterien

Konsistenz muss gewährleistet werden.
Ein hoher Datendurchsatz muss möglich sein.

==== Entscheidung

Neben Oracle wurde auch die Verwendung einer NoSQL-Datenbank in Betracht gezogen,
da diese eine hohe Skalierbarkeit und eine hohe Performance bietet.
Aufgrund der mangelnden Erfahrung und des kurzen Zeitplanes wird aber die bestehende
Oracle-DB verwendet.

=== Datenzugriff

==== Fragestellung

Wie soll auf die Daten zugegriffen werden?

==== Variante 1: Direkter Zugriff

Auf eine Zwischenschicht wird verzichtet und die SQL-Statements werden direkt ausgeführt.
Vorteil: Durch den Verzicht auf die Zwischenschicht ist eine höhere Performance möglich.
Nachteil: Änderungen an der DB-Struktur wirken sich direkt auf die Businesslogik aus.
Ein Teil der Businesslogik wird in die Persistenzschicht verlagert und Teile der
Persistierung wird durch die Businesslogik vorgenommen.

==== Variante 2: Object-Relational Mapping (ORM)

Mittels Object-Relational Mapping werden die Java-Objekte automatisch auf die Datenbanktabellen gemappt.
Der Zugriff auf die Datenbank ist daher gekapselt.
Ein häufig verwendeter OR-Mapper ist Hibernate.
footnote:[http://hibernate.org/orm/]

Vorteil: Standardkomponente, flexibel und robust

==== Variante 3: Hibernate und DAO

Der Zugriff auf die von Hibernate erstellten Entitäten erfolgt über eigene Datenklassen - den Data Access Objects (DAO).
Vorteil: Die Integrationsschicht wird vollständig von der Businesslogik getrennt.
Wenn sich das Datenmodell ändert, muss nur das entsprechende DAO angepasst werden.
Hibernate kann durch eine andere Technologie ersetzt werden,
beispielsweise wenn später auf NoSQL gewechselt werden sollte.
Nachteil: Es müssen die entsprechenden Klassen implementiert werden.
Durch jede weitere Zwischenschicht geht etwas Performance verloren.

==== Entscheidung

Wir haben uns für Variante 3 entschieden.
Die Vorteil der Flexibilität der DAOs überwiegt unserer Meinung nach den geringfügigen
Einfluss auf die Performance.

=== MVC-Pattern verwenden

==== Fragestellung

Wie wird sichergestellt, dass das GUI ausgetauscht werden kann?

==== Variante 1: JavaServer Faces
Vorteil: etabliertes Framework. Erleichtert die Umsetzung des MVC-Patterns.
Unterstützt bei der Umsetzung der Internationalisierung.

==== Variante 2: Single Page Application

Vorteil: Antwortzeiten können reduziert werden, da nur Teile der Webseite übertragen werden.
Die Benutzer können nicht manuell einzelne Seiten aufrufen, sondern können nur die auf
der aktuellen Webseite verfügbaren Links verwenden.

==== Entscheidung

Aufgrund der grösseren Erfahrung mit den JavaServer Faces wird diese Variante umgesetzt,
damit der Zeitplan eingehalten werden kann.


=== Performance der Boxoffice-User [[section-performance-box-office]]


==== Fragestellung

Wie wird sichergestellt, dass bei den Boxoffice-User die maximal zulässige Antwortzeit
immer eingehalten wird?

==== Rahmenbedingungen

* Ausser bei der Zahlungsabwicklung soll die Antwortzeit immer unter 2 Sekunden liegen.

* Es soll nur ein Server verwendet werden.

==== Betrachtete Alternativen

* Mehrere Applikationsserver auf dem physischen Server betreiben

* Neuverhandlung der Rahmenbedingungen, damit mindestens 2 Server betrieben werden können.

==== Entscheidung

Auch wenn die Kosten kurzfristig für die Ein-Server-Variante spricht,
empfehlen wir, dass mindestens zwei Server bereit gestellt werden.
Neben der besseren Verteilung der Last kann auch eine bessere Verfügbarkeit gewährleistet werden.
Wenn ein Server ausfällt, können die Benutzer auf den anderen Server umgeleitet werden.

=== Performance Sitzplatzreservation [[section-performance-sitzplatzreservierung]]

==== Fragestellung

Die Zuverlässigkeit des Reservationsablaufs ist einer der wichtigsten Faktoren für den Projekterfolg. Entscheidend
ist, dass einzelne Plätze nicht mehrmals verkauft werden und dass durch eine möglichst optimale Verteilung eine
hohe Anzahl an Plätzen anhand der Buchungswünsche verkauft werden können. Bei vielen simultanen Reservationen
muss der Algorithmus auch in der Lage sein, den geforderten Durchsatz zu erreichen.

Im Rahmen des SADs wurden daher mehrere Prototypen entwickelt auf ihre Funktionalität und Performance getestet.

.Die Performancetests wurden auf einem älteren Laptop (Lenovo T530) mit folgenden Hardware ausgeführt:
 * Intel Core i7-3630QM
 * 16 GB Systemspeicher

Die Resultate der Lasttests mit 100 parallelen Threads und jeweils 40 Anfragen pro Thread sind jeweils bei jeder Variante ersichtlich.

==== Rahmenbedingungen

Gemäss den Anforderungen (siehe <<QZ,Qualitätsziele>>) sollen 15'000 Plätze innerhalb von 10 Minuten verkauft werden können.
Das bedeutet das der Algorithmus rund rund 25 Reservationen pro Sekunden bei einer Antwortzeit von maximal zwei Sekunden ermöglichen muss.

Beim Buchen von Sitzplätzen dürfen zudem keine Überbuchungen entstehen und die Sitzplätze sollten (sofern noch vorhanden) benachbart sein.

==== Variante 1: Zufälliger Sitz wählen
Alle freie Sitzplätze der gewünschten Kategorie werden gelesen. Es wird mit einem zufälligen Platz begonnen, die benachbarten Plätze zu suchen. Falls genügende Plätze vorhanden sind, werden die Plätze reserviert. Sonst wird dieser Vorgang maximal 5 mal wiederholt..

Vorteil: kurze Latenzzeit.
Nachteil: viele Plätze sind nicht reserviert worden, reservierte Plätze sind fehlerhaft.
[source]
----
Strategy: RandomSeatSelectionStrategy
Seats
  available:     13660
  reserved:      12805
  remaining:     855
Reservations
  total:         4000
  rejected:      1468
  adjacent:      2228
  non-adjacent:  237
  incorrect:     67
Latency Time
  minimum:       0.0s
  maximum:       3.191s
  average:       0.657s
  deviation:     0.522s

Total Time:      26s
Throughput:      148 requests/s
----

==== Variante 2: Zufälliger Sektor wählen
Nur einen zufälligen Sektor der gewünschten Kategorie mit genügend freie Sitzplätze wird auswählt. Dann werden die benachbarte Plätze in diesem Sektor gesucht und falls genügende Plätze vorhanden sind, werden die Plätze reserviert und dabei wird ein Optimistic Locking beim persistieren verwendet.

Vorteil: kurze Latenzzeit.
Nachteil: viele Plätze sind nicht reserviert worden.
[source]
----
Strategy: RandomSectorSelectionStrategy
Seats
  available:     13660
  reserved:      11176
  remaining:     2484
Reservations
  total:         4000
  rejected:      1736
  adjacent:      2264
  non-adjacent:  0
  incorrect:     0
Latency Time
  minimum:       0.0s
  maximum:       2.076s
  average:       0.583s
  deviation:     0.229s

Total Time:      24s
Throughput:      166 requests/s
----

==== Variante 3: Sektoren mit zufälliger Reihenfolge
Alle Sektoren der gewünschten Kategorie mit genügend freien Sitzplätzen werden ausgelesen. Dann werden die Sektoren in einer zufälligen Reihenfolge gemischt. Die benachbarte Plätze werden in den Sektoren gesucht und falls genügende Plätze vorhanden sind, werden die Plätze reserviert. Dabei wird ein Optimistic Locking beim persistieren verwendet und beim Konflikt werden die Sitzplätze neu geladen.

Vorteil: mehr Plätze können reserviert werden.
Nachteil: relativ lange, maximale Latenzzeit.
[source]
----
Strategy: RandomOrderSectorStrategy
Seats
  available:     13660
  reserved:      11176
  remaining:     2484
Reservations
  total:         4000
  rejected:      1736
  adjacent:      2264
  non-adjacent:  0
  incorrect:     0
Latency Time
  minimum:       0.0s
  maximum:       6.876s
  average:       0.583s
  deviation:     0.229s

Total Time:      24s
Throughput:      166 requests/s
----

==== Variante 4: Cache basierte Lösung

Beim Starten des Systems wird als Singleton ein Cache erzeugt, der alle noch freien Sitzplätze einer Veranstaltung im
Arbeitsspeicher behält. Die Startzeit wird durch das Erstellen des Caches etwas erhöht,
dafür läuft der Reservierungsprozess danach sehr performant ab. Der Algorithmus sucht dabei jeweils einen Sektor der
noch genügend freie, nebeneinander liegende Plätze aufweist. Die Sitze werden danach aufsteigend von der tiefsten
Sitznummer aus reserviert. So ist es allerdings möglich das jeweils einzelne Sitze am Rande einer Reihe noch frei sind.
Reservierte Sitze werden danach aus dem Cache gelöscht und in der Datenbank ebenfalls als Reserviert markiert.
Durch Verwendung von Optimistic Locking beim persistieren wird sichergestellt,
dass der Algorithmus auch im Falle von mehreren Serverinstanzen niemals zweimal die gleichen Sitzplätze reserviert.
Als Cache wird das bewährte und quelloffene Produkt Ehcache verwendet. Mit Ehcache lassen sich die gecachten Daten auch
über mehrere Server replizieren, so dass die Lösung auch mit einer vertikalen Skalierung kompatibel wäre.

Vorteil: sehr hohe Performance
Nachteil: Hoher Resourcenbedarf, zusätzliche Komplexität

[source]
----
Strategy: CacheBasedSelectionStrategy
Seats
  available:     13660
  reserved:      13513
  remaining:     147
Reservations
  total:         4000
  rejected:      1400
  adjacent:      2600
  non-adjacent:  0
  incorrect:     0
Latency Time
  minimum:       0.0s
  maximum:       1.247s
  average:       0.287s
  deviation:     0.254s

Total Time:      11s
Throughput:      342 requests/s
----

==== Entscheidung

Alle Varianten erfüllen auf dem Testgerät die Anforderungen an den Datendurchsatz. Die Variante 1 und die Variante 2
haben allerdings eine hohe Anzahl von nicht verkauften Sitzplätzen und werden deshalb verworfen.


Die Anzahl der nicht reservierten Sitze sind in den Tests von Variante 3 und Variante 4 vergleichbar, der Durchsatz ist
allerdings bei Variante 4 fast drei mal höher. Da alle Daten bei Variante 4 gecacht werden, muss auf
dem Server wesentlich mehr Arbeitsspeicher vorhanden sein und die Java Virtual Machine (JVM) entsprechend konfiguriert werden.
Bei den Lasttests von Variante 4 musste der Arbeitsspeicher der JVM auf mindestens 1024 MB erhöht werden, ansonsten wurde das
Programm mit einem OutOfMemoryError unerwartet beendet.


Aufgrund der geringeren Komplexität des Algorithmus, des tieferen Resourcenbedarfs und der Tatsache das kein zusätzliches
Produkt (Ehcache) verwendet, konfiguriert und gewartet werden muss wurde die Entscheidung zugunsten von Variante 3 gefällt.

Um die Anzahl der frei bleibenden Sitze zu verringern wird der Algorithmus für die produktive Version noch so optimiert,
dass ebenfalls Einzelplätze gebucht werden können. Falls bei der Buchung keine genügend hohe Anzahl von nebeneinander liegenden
 Sitzen gefunden wird sollen dem Kunden beim Reservationsvorgang auch nicht adjazente Plätze angeboten werden.
