== Schutzbedarfsanalyse

OTS enthält wichtige Geschäftsinformationen die nur berechtigten Personen zugänglich sein dürfen.
Der Zugriff auf die Daten muss daher geschützt sein.
Eine hohe Verfügbarkeit der Anwendung muss gewährleistet sein. (siehe Anforderungen)
Gründsätzlich dürfen keine Passwörter im Klartext gespeichert sein.

=== Übersicht

Im Projekt müssen die in der Tabelle angegeben Punkte berücksichtigt werden.
Für die Bewertung werden 1, 2 oder 3 Punkte vergeben, wobei 1 geringer Schutzbedarf und 3 sehr hohen Schutzbedarf bedeutet.

|===
|Nummer | Bezeichnung | Bemerkung | Vertraulichkeit | Integrität | Verfügbarkeit | Nachvollziehbarkeit
|1| Personendaten | Kontaktdaten, Adresse, Anmeldedaten | 2 | 1 | 2 | 1
|2 | DB-Verbindung | | 3 | 1 | 2 | 1
|3 |Payment-Schnittstelle | DataTrans- Zugangsdaten |  |  |  |
|4 |Logdateien | DataTrans- Zugangsdaten |  |  |  |
|5 |Bestelldaten | z.B. reservierte Plätze |  |  |  |
|6 |Backups | |  |  |  |

|===


=== Erläuterungen

==== Personendaten
Es muss sichergestellt werden, dass nur berechtigte Sachbearbeiter die Kundendaten sehen und ändern kann.
Jeder Kunde dard nur seine eigenen Daten sehen und ändern.
Das Login-Passwort darf nur gehast in der Datenbank gespeichert werden.

==== DB-Verbindung
Auf die Datenbank darf nicht über das Internet direkt zugegriffen werden können.
Der Zugang erfolgt entweder über die Web-Applikation oder über das interne Admin-Tool.

==== Payment-Schnittstelle
Der Zahlungsvorgang wird durch einen externen Anbieter durchgeführt.
Daher werden keine Kreditkartennummer oder ähnliche Daten in der Datenbank gespeichert.
Die Übertragung der Daten muss mittels SSL gesichert werden.
Die Zugangsdaten zum externen Anbieter müssen verschlüsselt abgelegt werden.

Es muss sichergestellt sein, dass getätigte Zahlungen nicht verändert werden können.
Eine Archivierung der Zahlungsdaten ist nicht notwendig.

==== Logdateien
Die Logdateien dürfen keine personenbezogenen Daten enthalten.

==== Bestelldaten
Es muss sichergestellt sein, dass die Bestelldaten nicht nachträglich vom Kunden geändert werden können.
Nur Sachbearbeiter dürfen beispielsweise die Adresse korrigieren.


==== Backups & Archivierung
Es müssen in regelmässigen Abständen Backups erstellt werden, damit nach einem Ausfall der Datenbank nicht zu viele Daten verloren gehen.
Eine Archivierung der Daten ist nicht notwendig, für spätere Auswertungen aber wünschenswert.
