==== Abfragen

Unter _Abfragen_ verstehen wir Möglichkeit, wie der Datenschutzbeauftragte auf die Protokollierungsdaten zugreifen kann.

===== Eigene Applikation

Für die Auswertung wird eine eigene, auf die spezifischen Bedürfnisse des Datenschutzbeauftragten zugeschnittene Applikation gebaut.
Die Applikation kann dabei entweder intern oder von einem externen Dienstleister im Rahmen eines Auftrages entwickelt werden.

|===
| Vorteile | Nachteile

| Bedarfsgerechte Lösung möglich
| Hoher finanzieller Initialaufwand

| Kein Vendor-Lockin
| Weiterentwicklung  muss selbst gesteuert werden

| Sowohl mit Datenbank als auch mit Dateien als Speichermedium möglich
|

|===

===== Plain SQL-Abfragen

Dem Datenschützer wird eine SQL-Client und ein Datenbankuser mit ausschliesslich Leserechten auf die Tabellen, die die Protokollierungsdaten enhalten, gegeben.
 Diese Variante ist nur sinnvoll wenn die Protokollierungsdaten in der Datenbank gespeichert werden.

|===
| Vorteile | Nachteile

| Viele Auswertungsmöglichkeiten dank SQL
| SQL Know-How nötig, lokaler Client

| Wenig Implementierungsaufwand
| Usability

|
| Wenn eine zentrale Datenbank für alle Applikationen gemacht wird, kann via SQL auf alle Logdaten zugegriffen werden

|===

===== Logtool

Für die Auswertung von Logdateien existieren auf dem Markt sowohl kommerzielle (z.B. _Splunk_) als auch frei
verfügbare Tools (_ELK-Stack_), mit denen Logdateien von Applikationen schnell und komfortabel ausgewertet werden können.
Die Fachapplikationen könnten dabei die Anfragen und Mutationen in eigene Logdateien schreiben, die dann vom Logtool indexiert würden.
Dabei kann man feingranular konfigurieren, welcher  Benutzer auf welche Logdateien zugreifen kann.

Diese Lösung macht, wie der Name bereits impliziert, nur in Zusammenhang mit Logdateien Sinn.

|===
| Vorteile | Nachteile

| Bewährte Tools verfügbar
| Kommerzielle Lösungen (_Splunk_) teuer bei grossen Datenmengen (10 GB pro Tag 7800 USD)

| Keine Eigenentwicklung notwendig
| Keine strikte Trennung zwischen Applikationslogdaten (z.B. Fehler, Warnungen) und den Protokollierungsdaten


|===

===== Fazit

Die Variante _Plain SQL-Abfragen_ wird nicht weiter verfolgt, weil es SQL Know-How für den Datenschutzbeauftragten voraussetzt.
