==== Löschen

===== Logtool

Für die Auswertung von Logdateien existieren auf dem Markt sowohl kommerzielle (z.B. Splunk) als auch frei
verfügbare Tools (ELK-Stack), mit denene Logdateien von Applikationen schnell und komfortabel ausgewertet werden können.
Die Applikationen könnten dabei die Requests in eigene Logdateien schreiben, die dann vom Logtool indexiert würden.
 kann man feingranular konfigurieren, welcher  Benutzer auf welche Logdateien zugreifen kann.

|===
| Vorteile | Nachteile

| Bewährte Tools verfügbar
| Kommerzielle Lösungen (Splunk) sehr teuer bei grossen Datenmengen

| Keine Eigenentwicklung notwendig
|

|
|

|===

===== Eigene Anwendung

Für die Auswertung wird eine eigene, auf die spezifischen Fachbedürfnisse zugeschnittene Applikation gebaut.
Die Applikation kann dabei entweder intern oder von einem Dienstleister gebaut werden.

|===
| Vorteile | Nachteile

| Bedarfsgerechte Lösung notwendig
| Hoher Initialaufwand

| Kein Vendor-Lockin
| Weiterentwicklung  muss selbst gesteuert werden


|===

===== Plain SQL-Abfragen

Dem Datenschützer wird eine SQL-Client und ein Datenbankuser mit ausschliesslich Leserechten auf die Logtabellen
 gegeben. Diese Variante ist nur sinnvoll wenn die Persistierung der Logdatne in der Datenbank gemacht wird.

|===
| Vorteile | Nachteile

| Viele Auswertungsmöglichkeiten dank SQL
| SQL Know-How nötig

| Einfache Implementierung
| Usability


|===