=== Variante 4

==== Kontextdiagramm

==== Technologische Umsetzung

===== Abgreifen

Neue Bibliothek erstellen, die eine Möglichkeit zur Protokollierung bereitstellt.
Als Übergabeparameter werden die notwendigen Daten wie SecurityToken, den Methodenname, die Fachapplikation usw. übermittelt.
Die Protokollierungsdaten werden zunächst in eine lokale Textdatei gespeichert.
Pro Tag wird eine Datei erstellt.

Anhand des SecurityTokens wird geprüft, ob eine Protokollierung notwendig ist.
Die Bibliothek garantiert das nur nach einer erfolgreichen Protok
Falls ja, wird eine ID und der Status (OK, NOK, IGNORE) zurück gegeben.
Nur wenn als Status OK oder IGNORE zurückgeliefert wurde, wird die Fachapplikation die Daten abfragen bzw. mutieren.
Anschliessend wird eine weitere Methode der Bibliothek mit den Übergabeparametern ID und Abfrageergebnis aufgerufen, (wenn der Status OK ist).
Diese Daten werden ebenfalls in der Textdatei gespeichert.

*Vorteil*

hohe Performance, da zunächst nur in eine lokale Textdatei geschrieben wird.

Die Protokollierungen der einzelnen Fachapplikationen erfolgt unabhängig voneinander und können sich dadurch nicht gegenseitig behindern.

Es stehen sämtliche erforderlichen Protokollierungsdaten zur Verfügung.

*Nachteil*

Jede Fachapplikation muss angepasst werden und es muss sichergestellt werden, dass auch jede Fachapplikation den Aufruf durchführt.


===== Speichern

Es wird eine neue Applikation implementiert, die täglich die Daten der einzelnen Textdateien in einer zentralen Datenbank speichert.
Gleichzeitig wird das Abfrageergebnis beim ursprünglichen Eintrag ergänzt, damit es pro ID nur einen Datensatz gibt.
Wenn die Daten überführt wurden, wird die Textdatei gelöscht.
Dadurch wird sichergestellt, dass die Daten nur einmal eingelesen werden.
Wenn aus irgendeinen Grund die Daten nicht gespeichert werden konnten, können so aber auch Textdateien zu einem späteren Zeitpunkt eingelesen werden.

*Vorteile*

Die Daten stehen letztendlich an einer zentralen Stelle zur Verfügung, was die spätere Auswertung enorm erleichtert.

*Nachteile*

Zusätzliche Applikation notwendig.

Die Daten stehen erst mit einiger Verzögerung zur Auswertung zur Verfügung.

Es muss sichergestellt werden, dass alle Fachapplikationen berücksichtigt werden.

===== Abfragen

*Untervariante1 - Direkte Abfrage über die Datenbank*

Der Datenschutzbeauftragte erhält direkten Lesezugriff auf die Datenbank.

*Vorteile*

Es können beliebige Auswertungen vorgenommen werden.

Es muss nichts zusätzlich implementiert werden.


*Nachteil*

Der Datenschutzbeauftragte muss die erforderlichen SQL-Kenntnisse besitzen.

*Untervariante2 - Eigene Auswertungsapplikation*

Es wird eine neue Applikation für die Auswertung der Protokollierungsdaten implementiert

*Vorteile*

Der Datenschutzbeauftragte muss keine SQL-Kenntnisse besitzen.

Zusätzlich wäre es aber trotzdem möglich, die Eingabe von SQL-Statements zu erlauben, um die Vorteile der Variante 1 zu haben.

*Nachteile*

Zusätzlicher Implementierungsaufwand.


===== Löschen

Die Daten liegen zentral in einer Datenbank.
Es wird ein Datenbank-Job eingerichtet, der jede Nacht die Daten löscht, die älter als ein 1 Jahr sind.

*Vorteile*

Einfach einzurichten

Performant

*Nachteile*

Wenn sich der Zeitraum ändert, muss der Datenbank-Job angepasst werden.


==== Fazit

Die Lösung ist performant und ermöglicht durch die zentrale Ablage der Daten eine einfache Auswertung.

Nachteilig ist, dass alle Fachapplikationen angepasst werden müssen und nicht garantiert werden kann, dass alle Fachapplikationen die Protokollierungs-Bibliothek verwenden.

