=== Variante 4

==== Kontextdiagramm

==== Technologische Umsetzung

===== Abgreifen und Speichern

Neue Bibliothek erstellen, die eine Möglichkeit zur Protokollierung bereitstellt.
Als Übergabeparameter werden die notwendigen Daten wie SecurityToken, den Methodenname, die Fachapplikation usw. übermittelt.
Die Protokollierungsdaten werden zunächst in eine lokale Textdatei gespeichert.
Periodisch (z.B. pro Tag) wird eine Datei erstellt.

Anhand des SecurityTokens wird geprüft, ob eine Protokollierung notwendig ist.
Die Bibliothek garantiert, dass nur nach einer erfolgreichen Protokollierung die Abfragen bzw. die Mutationen durchgeführt werden.

Es wird eine neue Applikation implementiert, die periodisch die Protokollierungsdaten in einer zentralen Datenbank speichert.
Gleichzeitig wird das Abfrageergebnis beim ursprünglichen Eintrag ergänzt, damit es pro ID nur einen Datensatz gibt.
Nach der Verarbeitung wird die Textdatei gelöscht.

===== Abfragen

Es wird eine neue Applikation für die Auswertung der Protokollierungsdaten implementiert.

===== Löschen

Es wird ein Datenbank-Job eingerichtet, der periodisch die Daten löscht, die älter als die konfigurierte Zeit sind.


==== Vor- und Nachteile

Die Lösung ist performant und ermöglicht durch die zentrale Ablage der Daten eine einfache Auswertung.

Nachteilig ist, dass alle Fachapplikationen angepasst werden müssen.
Es ist ein relativ hoher Entwicklungsaufwand notwendig.
TODO: Lifecycle der Bibliothek --> Einfluss auf alle Applikationen

==== Risiken

Es muss sichergestellt werden, dass alle Fachapplikationen die Bibliothek verwenden.
